# Generated by Django 3.1.3 on 2020-12-02 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('employee_username', models.CharField(blank=True, default='admin', max_length=150, null=True)),
                ('serialno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('buying_price', models.FloatField()),
                ('actual_price', models.FloatField(blank=True, default=1, null=True)),
                ('selling_price', models.FloatField(blank=True, default=1, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('VAT', models.FloatField(default=16)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('date_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price_per_inventory', models.FloatField(blank=True, default=1, null=True)),
                ('total_vat_per_inventory', models.FloatField(blank=True, default=1, null=True)),
            ],
        ),
    ]
